### ISSUE TITLE
建议添加左右方括号翻页候选的选项

### ISSUE THREAD

**Issue by signdo** [libpinyin/ibus-libpinyin#402]
建议添加左右方括号翻页候选的选项, 以方便习惯使用 Windowns10 系统自带输入法的普通用户适应 Intelligent Pinyin.

**Comment by ithinkeng** [comment]
希望支持

**Comment by gaotongsh** [comment]
希望支持

**Comment by Huang-CL** [comment]
希望支持，以和mac默认输入法一致

**Comment by epico** [comment]
已经在代码中实现。

**Comment by Huang-CL** [comment]
谢谢！刚才看了一下没明白怎么更新。请问是不是必须等出release版本？repository根目录下没有configure文件。还是把没有的文件从旧的release里面复制过来就可以？

**Comment by epico** [comment]
ibus-libpinyin 1.15.94 已发布。

**Comment by Huang-CL** [comment]
@epico 
安装报错：

PYPinyinProperties.cc: In member function ‘gboolean PY::PinyinProperties::propertyActivate(const gchar*, guint)’:
PYPinyinProperties.cc:249:26: error: ‘m_props_lua_converter_vec’ was not declared in this scope
  249 |         for (auto iter = m_props_lua_converter_vec.begin ();
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by epico** [comment]
请安装 Lua 的开发包。

**Comment by Huang-CL** [comment]
抱歉再麻烦你。我安装之后不知道怎么调出新安装的版本。

我认为我安装成功了，make install之后正常退出，没有任何报错。
但是在输入法选择中，仍然只有系统自带的1.15.7版本。 安装新的输入法列表中，没有看到另外一个intelligent pinyin的选项。在/usr/local/share/中，没有找到一个可执行文件。尝试在setting->keyboard->input sources里面删除intelligent pinyin，重新安装，也还是旧的版本。在issue里面搜，也没搜到调出新的版本的方法。也尝试过重启，仍然没有解决问题。

**Comment by epico** [comment]
https://github.com/libpinyin/ibus-libpinyin/wiki/Installation

**Comment by Huang-CL** [comment]
我最先看到的就是这个wiki。但是我已经按照上面的步骤，把ibus-libpinyin都make install 完了，也没有报错。也确实新安装了一些东西在/usr/local/share/ibus-libpinyin/下面。
但是之后我还是找不到怎么调用这个新的版本。我打开的总还是旧的。

**Comment by epico** [comment]
试试将 libpinyin.xml 拷贝到 /usr/share/ibus/component .

推荐使用 Linux 发行版的包管理器来安装编译。

**Comment by Huang-CL** [comment]
原本安装完，我在/usr/local/share/ibus/component下面已经有如下的libpinyin.xml 了

<?xml version="1.0" encoding="utf-8"?>

<component>
	<name>org.freedesktop.IBus.Libpinyin</name>
	<description>Libpinyin Component</description>
	<exec>/usr/local/libexec/ibus-engine-libpinyin --ibus</exec>
	<version>1.15.94</version>
	<author>Peng Wu &lt;alexepico@gmail.com&gt;</author>
	<license>GPL</license>
	<homepage>https://github.com/libpinyin/ibus-libpinyin</homepage>
	<textdomain>ibus-libpinyin</textdomain>

	
	<observed-paths>
		<path>~/.config/ibus/libpinyin/engines.xml</path>
		<path>/usr/local/share/ibus-libpinyin/default.xml</path>
	</observed-paths>
    <engines exec="/usr/local/libexec/ibus-engine-libpinyin --xml" />
</component>

>推荐使用 Linux 发行版的包管理器来安装编译。

这是说用apt install来安装sqlite3，db, lua吗？我是用的apt install安装的。

**Comment by Huang-CL** [comment]
十分抱歉，之前是我看wiki不仔细。我configure的时候没有添加后面的安装路径--prefix=/usr
我重新安装了一遍，我怀疑这次是打开了正确的版本。但是现在我无法打开拼音的preference。所以看不了我到底运行的是哪个版本，我无法更改翻页键的设置。

**Comment by Huang-CL** [comment]
上面这条评论最后关于anaconda里面的python环境问题，用最后更新的方案还是不成功。
`conda install -c conda-forge pygobject`
确实安装了`gi`，但是重新运行`ibus-setup-libpinyin`，又会出现以下报错
```
Traceback (most recent call last):
  File "/usr/share/ibus-libpinyin/setup/main2.py", line 34, in <module>
    gi_require_version('Gtk', '3.0')
  File "/home/username/anaconda3/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```
运行`conda install -c conda-forge gtk3`后，又会出现新的以下报错
```
Traceback (most recent call last):                                                                        
  File "/usr/share/ibus-libpinyin/setup/main2.py", line 35, in <module>                                   
    gi_require_version('IBus', '1.0')                                                                     
  File "/home/username/anaconda3/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)                                            
ValueError: Namespace IBus not available    
```
这下我不知道怎么解决了。

不过相比于之前的修改ibus-setup-libpinyin文件的方法，我找到一个我认为更好的解决方案。
在安装ibus-libpinyin的时候，使用`./configure --prefix=/usr --with-python=/usr/bin/python` 来选择用ubuntu原生的python版本，而不用anaconda的。

但这之后，默认的`/usr/share/applications/ibus-setup-libpinyin.desktop`指向错误的`Exec=/usr/local/libexec/ibus-setup-libpinyin libpinyin`，需要修改成`Exec=/usr/libexec/ibus-setup-libpinyin libpinyin`
经过这些修改之后，在系统的setting->keyboard->input sources那里，可以打开preference。但是在桌面右上角的输入法图标那里，单击后的下拉菜单中的preference仍然打不开。不知什么原因。

**Comment by chemPolonium** [comment]
> 但是我的系统是装了python3-gi以及python3-gi-cairo的。之后发现，因为我在ubuntu里装了anaconda3，而且anaconda3的python是默认调用的。而anaconda3环境里没有gi。我尝试了不少方法，也没能成功在anaconda里面装上gi。我尝试通过更改PATH的顺序，把默认的python换成ubuntu系统自己的，但也没有效果。

Anaconda 对于系统确实会有一些侵入性的改变，要不启个虚拟机装个纯净的 Ubuntu 再试试能不能用？

如果确实是 Anaconda 的原因，那可能要开一个新的 Issue 讨论在 Anaconda 存在的情况下安装的兼容性问题。

**Comment by epico** [comment]
可以试试创建个新用户，重新下载，再编译一下试试。
