### ISSUE TITLE
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “ibus-libpinyin-preferences.ui”

### ISSUE THREAD

**Issue by hwypengsir** [libpinyin/ibus-libpinyin#460]
这个文件ibus-libpinyin-preferences.ui明明是存在的：
```
tree  /usr/share/ibus-libpinyin
/usr/share/ibus-libpinyin
├── base.lua
├── db
│   ├── english.db
│   ├── local.db
│   └── table.db
├── icons
│   ├── chinese.svg
│   ├── english.svg
│   ├── full-punct.svg
│   ├── full.svg
│   ├── half-punct.svg
│   ├── half.svg
│   ├── ibus-bopomofo.svg
│   ├── ibus-pinyin.svg
│   ├── simp-chinese.svg
│   └── trad-chinese.svg
├── network.txt
├── setup
│   ├── config.py
│   ├── dicttreeview.py
│   ├── ibus-libpinyin-preferences.ui
│   ├── keyboardshortcut.py
│   ├── main2.py
│   ├── __pycache__
│   │   ├── config.cpython-311.pyc
│   │   ├── dicttreeview.cpython-311.pyc
│   │   ├── keyboardshortcut.cpython-311.pyc
│   │   ├── main2.cpython-311.pyc
│   │   └── shortcuteditor.cpython-311.pyc
│   └── shortcuteditor.py
└── user.lua
```
为何出现错误？

```
python3  /usr/share/ibus-libpinyin/setup/main2.py
Traceback (most recent call last):
  File "/usr/share/ibus-libpinyin/setup/main2.py", line 687, in <module>
    main()
  File "/usr/share/ibus-libpinyin/setup/main2.py", line 683, in main
    PreferencesDialog(name).run()
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/ibus-libpinyin/setup/main2.py", line 78, in __init__
    self.__builder.add_from_file("ibus-libpinyin-preferences.ui")
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “ibus-libpinyin-preferences.ui”: No such file or directory (4)
```

**Comment by epico** [comment]
需要先切换到 `cd /usr/share/ibus-libpinyin/setup/` 目录，再运行 python .
